### ISSUE TITLE
Expose the plugin as custom command

### ISSUE THREAD

**Issue by jkribeiro** [jkribeiro/drupal-composer-paranoia-acquia#1]
Similar https://github.com/drupal-composer/drupal-paranoia/issues/2

**Comment by jkribeiro** [comment]
PR: https://github.com/jkribeiro/drupal-composer-paranoia-acquia/pull/2

**Comment by kmoll** [comment]
I have tested this and can confirm it is working as expected.

**Comment by jkribeiro** [comment]
great, thanks for your review and testing @kmoll.
